// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentList() {
  return window['go']['main']['App']['AgentList']();
}

export function KGGetGraph(arg1, arg2) {
  return window['go']['main']['App']['KGGetGraph'](arg1, arg2);
}

export function KGIndex(arg1, arg2) {
  return window['go']['main']['App']['KGIndex'](arg1, arg2);
}

export function KGInit(arg1, arg2) {
  return window['go']['main']['App']['KGInit'](arg1, arg2);
}

export function KGQuerySymbol(arg1, arg2) {
  return window['go']['main']['App']['KGQuerySymbol'](arg1, arg2);
}

export function KGStatus(arg1) {
  return window['go']['main']['App']['KGStatus'](arg1);
}

export function MemorySearch(arg1) {
  return window['go']['main']['App']['MemorySearch'](arg1);
}

export function MemoryStore(arg1) {
  return window['go']['main']['App']['MemoryStore'](arg1);
}

export function MemoryUpdate(arg1) {
  return window['go']['main']['App']['MemoryUpdate'](arg1);
}

export function ScaffoldInit(arg1) {
  return window['go']['main']['App']['ScaffoldInit'](arg1);
}

export function ScaffoldSkillAdd(arg1) {
  return window['go']['main']['App']['ScaffoldSkillAdd'](arg1);
}

export function ScaffoldSkillList() {
  return window['go']['main']['App']['ScaffoldSkillList']();
}

export function SelectRepository() {
  return window['go']['main']['App']['SelectRepository']();
}
