// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scaffold} from '../models';
import {kg} from '../models';
import {types} from '../models';

export function AgentList():Promise<Array<scaffold.AgentInfo>>;

export function KGIndex(arg1:string,arg2:kg.IndexOptions):Promise<kg.IndexResult>;

export function KGInit(arg1:string,arg2:boolean):Promise<void>;

export function KGQuerySymbol(arg1:string,arg2:string):Promise<Array<kg.Symbol>>;

export function KGStatus(arg1:string):Promise<kg.StatusResult>;

export function MemorySearch(arg1:types.SearchInput):Promise<types.SearchResult>;

export function MemoryStore(arg1:types.StoreInput):Promise<types.StoreResult>;

export function MemoryUpdate(arg1:types.UpdateInput):Promise<types.UpdateResult>;

export function ScaffoldInit(arg1:scaffold.InitOptions):Promise<scaffold.InitResult>;

export function ScaffoldSkillAdd(arg1:scaffold.SkillAddOptions):Promise<Array<scaffold.SkillAddResult>>;

export function ScaffoldSkillList():Promise<Array<string>>;
